### PR TITLE
Added Ctrl-a + Ctrl-e bindings.

### PR DESCRIPTION
**Pull request by skx**
These move to the start/end of the line, respectively.

### CODE REVIEW

**Comment by skx** [comment]
To be honest I was going to add more, specifically:

* HOME -> Start of file.
* END -> End of file.
* Ctrl-k -> Kill to end of line
* Ctrl-u -> Kill to start of line.

But I realize these might make things overly-complex, and be against the spirit of the editor.  Plus of course these bindings might be personal-taste...

**Comment by skx** [comment]
See also #13, which contains a snippet for "`Ctrl-x`" binding for deleting the current line.

(That particular binding would drive me mad, but I guess its an example of more bindings by default.)

I will resist the temptation to bind keystrokes to Lua functions ;)

**Comment by kristofer** [comment]
it'd be sweet to have a keymap of some kind, (I know, I know, 1024 LOC)

**Comment by skx** [comment]
Rework the application to implement some primitives:

* count_lines
* forward_line / backward_line
* forward_char / backward_char
* load_file
* save_file
* insert_char( char c )

Then move all the logic into an external lua file.  I bet that could be done in in a reasonable amount of code.  Though perhaps only 1k if we counted the core, not the external lua, or the (trivial) binding.

**Comment by skx** [comment]
I was optimistic.  I wrote some glue to allow Lua to process keystrokes, via an `on_key` function.  My definition looks like this:

     function on_key(k)
         if ( string.byte(k) == 1 ) then sol()
         elseif ( string.byte(k) == 5 ) then  eol()
         else  insert(k)   end
     end
     -- Called at load-time
     insert( "Lua support is cool!" )

Here "1" == Ctrl-a, and 5 == Ctrl-e.  Total line-count is now 1350 lines.  Meh.

That includes:

* Setup of Lua
* Loading `kilo.lua` on startup
* Three new functions exported to Lua
    * insert(str)  -> Insert the string into the editor
    * start-of-line() / sol() -> Move cursor to start of line.
    * end-of-line() / eol() -> Move cursor to end of line.

I guess adding more bindings to handle get/set of cursor position, save, load, etc, will similarly increase the code-size.  Shame.

**Comment by skx** [comment]
I'll stop updating here; but if you wish to see my work:

* https://github.com/skx/kilo
* The default [kilo.lua](https://github.com/skx/kilo/blob/master/kilo.lua) file.

I suspect there's a choice to be made though, regarding keymaps and bindings which is more general than this pull-request though, especially if you want to sidestep any debate about "Emacs bindings" vs "vi-bindings".  Either do it properly, or not at all.  Having Lua might be a step too far, but I think it might be worthwhile to allow flexible extensions.

Obviously integrating Lua completely might turn people off, but it would allow syntax-handling to be outside the main binary, for example.   This function shows what might be possible:

   -- "Ctrl-d" inserts the current data the cursor position.
   keymap['^D'] = function() insert( os.date() ) end

Or how about:

    keymap['^M'] = os.execute( "make" )

**Pull request closed without merging**
